Cache
rosberry/texstyle pull request #18
Opened 2020-02-06 09:36 UTC by artemnovichkov

Update README with the cache logic description. Related to #14. BTW, add missing texts for arrays.

2020-02-06 09:50 UTC, stason314 approved these changes

2020-02-11 05:52 UTC, ntunin approved these changes

2020-02-13 11:03 UTC, ReshetovE approved these changes

2020-02-17 10:57 UTC, stason314 requested changes

2020-02-17 10:57 UTC, stason314 commented on Texstyle/Texstyle/ControlStateText.swift
> +           observeStyles()
`observeStyles()` was already called in `init(value: value, styles: styles)`. Should you call it here?

2020-02-17 10:57 UTC, stason314 commented on Texstyle/Texstyle/ControlStateText.swift
> +        substyles.forEach { (state, substyles) in
```suggestion
        substyles.forEach { state, substyles in
```

2020-02-17 10:57 UTC, stason314 commented on Texstyle/Texstyle/ControlStateText.swift
> +        styles.forEach { (_, style) in
```suggestion
        styles.forEach { _, style in
```

2020-02-17 10:57 UTC, stason314 commented on Texstyle/Texstyle/ControlStateText.swift
> +        substyles.forEach { (_, substyles) in
```suggestion
        substyles.forEach { _, substyles in
```

2020-02-17 10:57 UTC, stason314 commented on Texstyle/Texstyle/Text.swift
> +            observeStyles()
Should you call it there ?

2020-03-13 09:29 UTC, ReshetovE approved these changes

2020-03-24 10:34 UTC, stason314 approved these changes

2020-04-01 11:49 UTC, stason314 approved these changes

2020-07-03 10:34 UTC, Antowkos commented
@zhvrnkov, please add your review here

2020-07-17 04:20 UTC, ntunin commented
@disabled Can you provide your feedback?

2020-07-24 05:05 UTC, ntunin commented
@Antowkos @disabled

2020-07-24 10:27 UTC, merged